version: '3.3'
networks:
  gorod_rabot_test_network:
    driver: bridge
services:
  gorod_rabot_test_nginx:
    image: nginx:1.27-alpine
    container_name: gorod_rabot_test_nginx
    restart: on-failure
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/config/:/etc/nginx/conf.d
      - ./docker/nginx/logs/:/var/log/nginx
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    networks:
      - gorod_rabot_test_network
  gorod_rabot_test_php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: gorod_rabot_test_php
    restart: on-failure
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./docker/php/config/conf.d:/.config
      - ./docker/php/config/extend-php.ini:/usr/local/etc/php/conf.d/extend-php.ini
    depends_on:
      - gorod_rabot_test_mysql
    networks:
      - gorod_rabot_test_network
  gorod_rabot_test_mysql:
    image: mysql:8.4
    container_name: gorod_rabot_test_mysql
    restart: on-failure
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - gorod_rabot_test_network
